### ISSUE TITLE
The nepal link includes South Sudan dataset

### ISSUE THREAD

**Issue by DitaA** [luiscape/hdxscraper-unosat#1]
Your shared [link for Nepal](https://data.hdx.rwlabs.org/organization/un-operational-satellite-appplications-programme-unosat?q=nepal) includes two South Sudan datasets in the bottom. Is this intentional?

**Comment by luiscape** [comment]
The reason is that the description of the two South Sudan datasets contain the word "Nepal". Here's an example: 

```
.. 14,000 persons and the adjacent UNMISS base includes troops from India, **Nepal**, 
South Korea, and Rwanda. 
```

Notice the `Nepal` there. CKAN is showing search results for "Nepal". If we use the filter by country that problem doesn't happen: https://data.hdx.rwlabs.org/organization/ba5aacba-0633-4364-9528-bc76a3f6cf95?groups=npl

I'm closing this issue.
